version: '3.8'

services:
  proxy:
    container_name: proxy
    image: traefik:alpine
    restart: always
    labels:
      - "traefik.frontend.rule=Host:monitor.traefik"
      - "traefik.port=8080"
      - "traefik.enabled=true"
      - "traefik.backend.healthcheck.enable=false"
      - "traefik.docker.network=proxy"
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:8080:8080
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"


networks:
  default:
    external: true
    name: proxy
