logLevel = "DEBUG"

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"

    [entryPoints.http.http.redirections.entryPoint]
      to = "https"
      scheme = "https"
  
  [entryPoints.https]
    address = ":443"

[api]
  dashboard = true
  insecure = true
  debug = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  network = "proxy"
  useBindPortIP = true
  exposedbydefault = true

[certificatesResolvers.letsencrypt.acme]
  email = "ashraf.majdee@gmail.com"
  storage = "/letsencrypt/acme.json"

  [certificatesResolvers.letsencrypt.acme.tlsChallenge]

  [certificatesResolvers.letsencrypt.acme.httpchallenge]
    entryPoint = "http"
